from typing import Any, Dict, List

ISO_COUNTRIES = ['United States',
 'Canada',
 'Mexico',
 'United Kingdom',
 'Germany',
 'France',
 'Australia',
 'Japan']

PAGES: List[Dict[str, Any]] = [{'key': 'broker_dealer_relationships',
  'sections': [{'fields': [{'label': 'Employee of this Broker-Dealer?',
                            'name': 'employee_this_bd',
                            'options': ['Yes', 'No'],
                            'required': True,
                            'type': 'radio'},
                           {'fields': [{'label': 'Employee Name',
                                        'name': 'employee_name',
                                        'required': True,
                                        'type': 'text'},
                                       {'label': 'Department',
                                        'name': 'department',
                                        'required': False,
                                        'type': 'text'},
                                       {'label': 'Branch',
                                        'name': 'branch',
                                        'required': False,
                                        'type': 'text'},
                                       {'label': 'Start Date',
                                        'name': 'start_date',
                                        'required': True,
                                        'type': 'date',
                                        'validate': 'iso_date'}],
                            'show_if': {'employee_this_bd': 'Yes'},
                            'type': 'group'},
                           {'label': 'Related to an Employee of this Broker-Dealer?',
                            'name': 'related_this_bd',
                            'options': ['Yes', 'No'],
                            'required': True,
                            'type': 'radio'},
                           {'fields': [{'label': 'Employee Name',
                                        'name': 'related_employee_name',
                                        'required': True,
                                        'type': 'text'},
                                       {'label': 'Relationship',
                                        'name': 'relationship',
                                        'options': ['Spouse',
                                                    'Parent',
                                                    'Child',
                                                    'Sibling',
                                                    'Other'],
                                        'required': True,
                                        'type': 'select'},
                                       {'label': 'Branch',
                                        'name': 'branch_related',
                                        'required': False,
                                        'type': 'text'}],
                            'show_if': {'related_this_bd': 'Yes'},
                            'type': 'group'},
                           {'label': 'Employee of another Broker-Dealer?',
                            'name': 'employee_other_bd',
                            'options': ['Yes', 'No'],
                            'required': True,
                            'type': 'radio'},
                           {'fields': [{'label': 'Firm Name',
                                        'name': 'firm_name_other',
                                        'required': True,
                                        'type': 'text'},
                                       {'label': 'CRD #',
                                        'name': 'crd_other',
                                        'required': True,
                                        'type': 'text',
                                        'validate': 'crd'},
                                       {'label': 'Role',
                                        'name': 'role_other',
                                        'required': False,
                                        'type': 'text'},
                                       {'label': 'Start Date',
                                        'name': 'start_date_other',
                                        'required': False,
                                        'type': 'date',
                                        'validate': 'iso_date'}],
                            'show_if': {'employee_other_bd': 'Yes'},
                            'type': 'group'},
                           {'label': 'Related to an employee of another Broker-Dealer?',
                            'name': 'related_other_bd',
                            'options': ['Yes', 'No'],
                            'required': True,
                            'type': 'radio'},
                           {'fields': [{'label': 'Firm Name',
                                        'name': 'firm_name_rel',
                                        'required': True,
                                        'type': 'text'},
                                       {'label': 'Employee Name',
                                        'name': 'employee_name_rel',
                                        'required': True,
                                        'type': 'text'},
                                       {'label': 'Relationship',
                                        'name': 'relationship_rel',
                                        'options': ['Spouse',
                                                    'Parent',
                                                    'Child',
                                                    'Sibling',
                                                    'Other'],
                                        'required': True,
                                        'type': 'select'}],
                            'show_if': {'related_other_bd': 'Yes'},
                            'type': 'group'}],
                'title': 'Associations'}],
  'title': 'Broker-Dealer Relationships'},
 {'key': 'reg_affiliations',
  'sections': [{'fields': [{'label': 'Member of Stk Exch./FINRA?',
                            'name': 'sro_member',
                            'options': ['Yes', 'No'],
                            'required': True,
                            'type': 'radio'},
                           {'fields': [{'label': 'Membership Type',
                                        'name': 'membership_type',
                                        'options': ['FINRA', 'NYSE', 'NASDAQ', 'Other'],
                                        'required': True,
                                        'type': 'select'},
                                       {'label': 'CRD #',
                                        'name': 'sro_crd',
                                        'required': False,
                                        'type': 'text',
                                        'validate': 'crd'},
                                       {'label': 'Branch',
                                        'name': 'sro_branch',
                                        'required': False,
                                        'type': 'text'}],
                            'show_if': {'sro_member': 'Yes'},
                            'type': 'group'},
                           {'label': 'Are you a senior officer, director, or 10% or more '
                                     'shareholder of a public company?',
                            'name': 'control_person',
                            'options': ['Yes', 'No'],
                            'required': True,
                            'type': 'radio'},
                           {'fields': [{'label': 'Company Name',
                                        'name': 'company_name',
                                        'required': True,
                                        'type': 'text'},
                                       {'label': 'Ticker',
                                        'name': 'ticker',
                                        'required': False,
                                        'type': 'text',
                                        'validate': 'ticker'},
                                       {'label': 'Exchange',
                                        'name': 'exchange',
                                        'options': ['NYSE', 'NASDAQ', 'AMEX', 'Other'],
                                        'required': False,
                                        'type': 'select'},
                                       {'label': 'Role',
                                        'name': 'role',
                                        'required': False,
                                        'type': 'text'},
                                       {'label': 'Ownership %',
                                        'name': 'ownership_pct',
                                        'required': False,
                                        'type': 'number',
                                        'validate': 'pct_0_100_two_dec'},
                                       {'label': 'As Of',
                                        'name': 'as_of',
                                        'required': False,
                                        'type': 'date',
                                        'validate': 'iso_date'}],
                            'show_if': {'control_person': 'Yes'},
                            'type': 'group'}],
                'title': 'SRO Membership & Control Persons'}],
  'title': 'Regulatory Affiliations'},
 {'key': 'foreign_accounts',
  'sections': [{'fields': [{'label': 'Foreign Financial Institution Account?',
                            'name': 'has_ffi',
                            'options': ['Yes', 'No'],
                            'required': True,
                            'type': 'radio'},
                           {'fields': [{'label': 'Institution Name',
                                        'name': 'institution_name',
                                        'required': True,
                                        'type': 'text'},
                                       {'label': 'Country',
                                        'name': 'country',
                                        'options': 'ISO_COUNTRIES',
                                        'required': True,
                                        'type': 'select'},
                                       {'label': 'Purpose',
                                        'name': 'purpose',
                                        'options': ['Savings', 'Brokerage', 'Payments', 'Other'],
                                        'required': True,
                                        'type': 'select'},
                                       {'label': 'Source of Funds',
                                        'name': 'source_of_funds',
                                        'required': False,
                                        'type': 'textarea'},
                                       {'label': 'Open Date',
                                        'name': 'open_date',
                                        'required': False,
                                        'type': 'date',
                                        'validate': 'iso_date'},
                                       {'label': 'Is this a private banking account?',
                                        'name': 'private_banking',
                                        'options': ['Yes', 'No'],
                                        'required': False,
                                        'type': 'radio'},
                                       {'label': 'Is this an account for a Foreign Bank?',
                                        'name': 'foreign_bank_acct',
                                        'options': ['Yes', 'No'],
                                        'required': False,
                                        'type': 'radio'}],
                            'show_if': {'has_ffi': 'Yes'},
                            'type': 'group'}],
                'title': 'FFI / Private Banking'}],
  'title': 'Foreign Financial Accounts'},
 {'key': 'pep',
  'sections': [{'fields': [{'label': 'Politically Exposed Person?',
                            'name': 'is_pep',
                            'options': ['Yes', 'No'],
                            'required': True,
                            'type': 'radio'},
                           {'fields': [{'label': 'PEP Name',
                                        'name': 'pep_name',
                                        'required': True,
                                        'type': 'text'},
                                       {'label': 'Country',
                                        'name': 'pep_country',
                                        'options': 'ISO_COUNTRIES',
                                        'required': True,
                                        'type': 'select'},
                                       {'label': 'Relationship',
                                        'name': 'pep_relationship',
                                        'options': ['Self', 'Family', 'Associate'],
                                        'required': True,
                                        'type': 'select'},
                                       {'label': 'Title',
                                        'name': 'pep_title',
                                        'required': False,
                                        'type': 'text'},
                                       {'label': 'Start Date',
                                        'name': 'pep_start',
                                        'required': False,
                                        'type': 'date',
                                        'validate': 'iso_date'},
                                       {'label': 'End Date',
                                        'name': 'pep_end',
                                        'required': False,
                                        'type': 'date',
                                        'validate': 'iso_date>=pep_start'},
                                       {'label': 'I consent to screening',
                                        'name': 'pep_screening_consent',
                                        'required': True,
                                        'type': 'checkbox'}],
                            'show_if': {'is_pep': 'Yes'},
                            'type': 'group'}],
                'title': 'PEP Screening'}],
  'title': 'Politically Exposed Person (PEP)'}]
